base_admin_home:
    path:     /
    defaults: { _controller: BaseBundle:Admin:index }
    requirements:
        _method: GET

base_admin_ajouter_article:
    path:     /ajouter
    defaults: { _controller: BaseBundle:AdminArticle:ajouter }
    requirements:
        _method: GET|POST

base_admin_modifier_article:
    path:     /modifier
    defaults: { _controller: BaseBundle:AdminArticle:modifier }
    requirements:
        _method: GET|POST

base_admin_supprimer_article:
    path:     /supprimer
    defaults: { _controller: BaseBundle:AdminArticle:supprimer }
    requirements:
        _method: DELETE